version: '3.9'

services:
  authsvc:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://auth:secret@postgres:5432/auth?sslmode=disable
      - JWT_SECRET=supersecret
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER=auth
      POSTGRES_PASSWORD=secret
      POSTGRES_DB=auth
    ports:
      - "5432:5432"
